---
abstract: 'testing TCP program'
author:
  - 'Tokuhiro Matsuno <tokuhirom@gmail.com>'
build_requires:
  File::Temp: 0
  Socket: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.4.5, CPAN::Meta::Converter version 2.131490'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-TCP
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Net::EmptyPort:
    file: lib/Net/EmptyPort.pm
  Test::TCP:
    file: lib/Test/TCP.pm
    version: 2.01
  Test::TCP::CheckPort:
    file: lib/Test/TCP/CheckPort.pm
requires:
  IO::Socket::INET: 0
  Test::More: 0
  Test::SharedFork: 0.19
  Time::HiRes: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/tokuhirom/Test-TCP/issues
  homepage: https://github.com/tokuhirom/Test-TCP
  repository: git://github.com/tokuhirom/Test-TCP.git
version: 2.01
x_contributors:
  - 'tokuhirom <tokuhirom@d0d07461-0603-4401-acd4-de1884942a52>'
  - 'mattn <mattn@d0d07461-0603-4401-acd4-de1884942a52>'
  - 'yappo <yappo@d0d07461-0603-4401-acd4-de1884942a52>'
  - '奥 一穂 <kazuho@EM114-48-138-123.pool.e-mobile.ne.jp>'
  - 'gfx <gfuji@cpan.org>'
  - 'Kenichi Ishigaki <ishigaki@cpan.org>'
  - 'lestrrat <lestrrat+github@gmail.com>'
  - 'Masahiro Nagano <kazeburo@gmail.com>'
  - 'Thomas Klausner <domm@plix.at>'
  - 'Brendan Byrd <Perl@ResonatorSoft.org>'
  - 'Pavel Shaydo <zwon@cpan.org>'
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
  - 'Christian Walde <walde.christian@googlemail.com>'
