--- #YAML:1.0
name:               Net-Server
version:            2.007
abstract:           Extensible, general Perl server engine
author:
    - Paul Seamons (paul@seamons.com) and Rob Brown (bbb@cpan.org)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    IO::Socket:  0
    POSIX:       0
    Socket:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
