---
abstract: "boost Cookie::Baker's crush_cookie"
author:
  - 'Masahiro Nagano <kazeburo@gmail.com>'
build_requires:
  Test::More: '0.98'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Minilla/v2.4.1, CPAN::Meta::Converter version 2.141170'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Cookie-Baker-XS
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Cookie::Baker::XS:
    file: lib/Cookie/Baker/XS.pm
    version: '0.06'
requires:
  Exporter: '0'
  perl: '5.008001'
resources:
  bugtracker: https://github.com/kazeburo/Cookie-Baker-XS/issues
  homepage: https://github.com/kazeburo/Cookie-Baker-XS
  repository: git://github.com/kazeburo/Cookie-Baker-XS.git
version: '0.06'
