---
abstract: 'temporary buffer to save bytes'
author:
  - 'Tatsuhiko Miyagawa'
build_requires:
  ExtUtils::MakeMaker: 6.36
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Stream-Buffered
no_index:
  directory:
    - inc
    - t
resources:
  bugtracker: https://github.com/plack/Plack/issues
  homepage: http://plackperl.org
  license: http://dev.perl.org/licenses/
  repository: git://github.com/doy/stream-buffered.git
version: 0.02
