---
abstract: 'Self Contained SQLite RDBMS in a DBI Driver'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  File::Spec: 0.82
  Test::More: 0.42
configure_requires:
  DBI: 1.57
  ExtUtils::MakeMaker: 6.48
  File::Spec: 0.82
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBD-SQLite
no_index:
  directory:
    - t
    - inc
    - util
requires:
  DBI: 1.57
  Tie::Hash: 0
resources:
  MailingList: http://lists.scsys.co.uk/cgi-bin/mailman/listinfo/dbd-sqlite
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=DBD-SQLite
  license: http://dev.perl.org/licenses/
  repository: https://github.com/DBD-SQLite/DBD-SQLite
version: 1.40
