---
abstract: 'Checks to see if the module can be loaded'
author:
  - 'Tokuhiro Matsuno <tokuhirom @*(#RJKLFHFSDLJF gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.3, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Requires
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Test::Requires:
    file: lib/Test/Requires.pm
    version: 0.07
requires:
  Test::Builder::Module: 0
  Test::More: 0.61
  perl: 5.008_001
resources:
  bugtracker: https://github.com/tokuhirom/Test-Requires/issues
  homepage: https://github.com/tokuhirom/Test-Requires
  repository: git://github.com/tokuhirom/Test-Requires.git
version: 0.07
x_contributors:
  - 'Tatsuhiko Miyagawa <miyagawa@bulknews.net>'
  - 'gfx <gfuji@cpan.org>'
  - 'Toby Inkster <mail@tobyinkster.co.uk>'
  - 'tokuhirom <tokuhirom@gmail.com>'
