---
abstract: unknown
author:
  - 'Fergal Daly <fergal@esatclear.ie>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Deep
no_index:
  directory:
    - t
    - inc
requires:
  List::Util: 1.09
  Scalar::Util: 1.09
  Test::More: 0
  Test::NoWarnings: 0.02
  Test::Tester: 0.04
version: 0.110
