---
abstract: 'An object representing a stack trace'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Test::More: 0.88
  base: 0
  bytes: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Devel-StackTrace
requires:
  File::Spec: 0
  Scalar::Util: 0
  overload: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Devel-StackTrace
  repository: git://git.urth.org/Devel-StackTrace.git
version: 1.30
